// Automatic navigation graph for bots. Nodes are generated by sampling a grid over the arena
// and scanning every column top-down for walkable surfaces with standing headroom; links are
// found by sweeping a capsule between neighbours using the same collision world the player
// moves through. Link types:
//   walk — plain walking (stairs, ramps, small steps <= MOVE.stepHeight)
//   jump — ledge 0.46..1.3 m higher that the player can mantle (hold jump while pushing into it)
//   drop — one-way walk off an edge onto walkable ground up to ~5 m below
//   pad  — jump pad: from the node on the pad to the simulated ballistic landing point
import * as THREE from 'three';

const DEFAULTS = {
  spacing: 1.5, // grid spacing (m)
  radius: 0.36, // clearance for nodes (player collider half-width)
  linkRadius: 0.34, // capsule half-width used when sweeping links
  height: 1.8, // standing height
  crouchHeight: 1.15,
  stepUp: 0.46, // MOVE.stepHeight
  sample: 0.4, // sweep sample spacing
  maxDrop: 5.0,
  jumpMin: 0.46,
  jumpMax: 1.3, // mantle reach (MOVE.mantleMax is 1.35)
  walkLink: 2.6, // max horizontal walk/jump link length
  dropLink: 3.4, // max horizontal drop link length
  gravity: 20, // MOVE.gravity
  smoothRange: 16, // max straight-line skip when smoothing paths
};

const TYPE_ID = { walk: 0, jump: 1, drop: 2, pad: 3 };
const TYPE_NAME = ['walk', 'jump', 'drop', 'pad'];
const CORNERS = [[-0.22, -0.22], [0.22, -0.22], [-0.22, 0.22], [0.22, 0.22]];
const NUDGES = [];
for (const r of [0.4, 0.72]) {
  for (let i = 0; i < 8; i++) {
    const a = (i / 8) * Math.PI * 2;
    NUDGES.push([Math.round(Math.cos(a) * r * 1000) / 1000, Math.round(Math.sin(a) * r * 1000) / 1000]);
  }
}

const _o = new THREE.Vector3();
const _d = new THREE.Vector3();
const _p = new THREE.Vector3();

const nowMs = () => (typeof performance !== 'undefined' ? performance.now() : Date.now());
const cellKey = (ix, iz) => (ix + 4096) * 8192 + (iz + 4096);

export class NavGraph {
  constructor(world, opts = {}) {
    this.world = world;
    this.opts = { ...DEFAULTS, ...opts };
    this.nodes = [];
    this.pads = [];
    this.stats = { nodes: 0, links: 0, walk: 0, jump: 0, drop: 0, pad: 0, pruned: 0, buildMs: 0 };
    this._grid = new Map();
    this._cand = [];
    this._heap = [];
    this._heapF = [];
  }

  // ------------------------------------------------------------------ build
  static build(world, arena, opts = {}) {
    const t0 = nowMs();
    const g = new NavGraph(world, opts);
    const o = g.opts;
    const b = arena?.bounds || world.bounds;
    const pads = world.jumpPads || [];
    g.pads = pads;
    g._buildGrid = new Map();
    g._tmpNodes = [];

    // 1) grid columns: every walkable surface with headroom
    const s = o.spacing;
    const ix0 = Math.ceil((b.min.x + 0.3) / s), ix1 = Math.floor((b.max.x - 0.3) / s);
    const iz0 = Math.ceil((b.min.z + 0.3) / s), iz1 = Math.floor((b.max.z - 0.3) / s);
    const yTop = b.max.y - 0.05, yBot = b.min.y - 0.6;
    for (let ix = ix0; ix <= ix1; ix++) {
      for (let iz = iz0; iz <= iz1; iz++) {
        const x = ix * s, z = iz * s;
        let y = yTop;
        for (let guard = 0; guard < 24 && y > yBot; guard++) {
          const gh = world.groundHeight(x, y, z, 0.05, 0, y - yBot);
          if (!gh) break;
          g._trySurface(x, gh.y, z, gh.collider);
          y = gh.y - 0.12;
        }
      }
    }

    // 2) seeds: pads, pad landings, pickups, spawns (guarantee nodes at the places that matter)
    const padNodes = [];
    pads.forEach((pad, i) => {
      const cx = (pad.min.x + pad.max.x) / 2, cz = (pad.min.z + pad.max.z) / 2;
      const gh = world.groundHeight(cx, pad.max.y, cz, 0.05, 0, 2);
      const y = gh ? gh.y : pad.min.y;
      const n = g._addNode(cx, y, cz);
      n.pad = i;
      const land = g._simulatePad(pad, cx, y, cz);
      padNodes.push({ node: n, land });
      if (land) {
        const ln = g._seed(land.pos);
        if (ln) ln.landing = true;
      }
    });
    if (arena?.pickups) for (const p of arena.pickups) { const n = g._seed(p.pos); if (n) n.pickup = p.id; }
    if (arena?.spawns) for (const sp of arena.spawns) g._seed(sp.pos);

    // 3) links
    const tmp = g._tmpNodes;
    const R = Math.ceil(Math.max(o.walkLink, o.dropLink) / s);
    for (const a of tmp) {
      if (a.pad >= 0) continue; // you cannot walk off a jump pad: the only way out is the pad link
      const cx = Math.round(a.pos.x / s), cz = Math.round(a.pos.z / s);
      for (let dx = -R; dx <= R; dx++) {
        for (let dz = -R; dz <= R; dz++) {
          const cell = g._buildGrid.get(cellKey(cx + dx, cz + dz));
          if (!cell) continue;
          for (const bn of cell) {
            if (bn === a) continue;
            const hx = bn.pos.x - a.pos.x, hz = bn.pos.z - a.pos.z;
            const d = Math.hypot(hx, hz);
            if (d > o.dropLink || d < 0.05) continue;
            const dy = bn.pos.y - a.pos.y;
            let walked = false;
            if (Math.abs(dy) <= 0.62 + d * 0.62 && d <= o.walkLink) { // ramps & stairs climb up to ~32 deg
              if (bn.pad >= 0) {
                const r = g._walkTest(a.pos, bn.pos, o.linkRadius, bn.pad);
                if (r && r.rise <= o.stepUp + 0.01) { g._link(a, bn, 'walk'); walked = true; }
              } else if (a.id < bn.id) {
                const r = g._walkTest(a.pos, bn.pos, o.linkRadius, -1);
                if (r) {
                  if (r.rise <= o.stepUp + 0.01) { g._link(a, bn, 'walk'); walked = true; }
                  if (r.fall <= o.stepUp + 0.01) g._link(bn, a, 'walk');
                  else g._link(bn, a, 'jump');
                }
              } else walked = a.links.some((l) => l.node === bn);
            }
            if (walked || bn.pad >= 0) continue;
            if (dy < -0.62 && dy >= -o.maxDrop) {
              if (g._dropTest(a.pos, bn.pos, o.linkRadius)) g._link(a, bn, 'drop');
            } else if (dy > o.jumpMin && dy <= o.jumpMax && d <= o.walkLink) {
              if (g._jumpTest(a.pos, bn.pos, o.linkRadius)) g._link(a, bn, 'jump');
            }
          }
        }
      }
    }

    // 4) pad links: pad node -> node nearest to the simulated landing point
    for (const { node, land } of padNodes) {
      if (!land) continue;
      const ln = g._nearestBuild(land.pos, 2.5, 0.7, node);
      if (ln) g._link(node, ln, 'pad', land.length + 0.5);
    }

    // 5) prune: keep the largest connected component plus everything reachable from it
    g._finalize();
    g.stats.buildMs = Math.round((nowMs() - t0) * 10) / 10;
    delete g._buildGrid;
    delete g._tmpNodes;
    return g;
  }

  _addNode(x, y, z) {
    const n = { id: this._tmpNodes.length, pos: new THREE.Vector3(x, y, z), links: [], pad: -1, pickup: -1, landing: false };
    this._tmpNodes.push(n);
    const k = cellKey(Math.round(x / this.opts.spacing), Math.round(z / this.opts.spacing));
    let cell = this._buildGrid.get(k);
    if (!cell) { cell = []; this._buildGrid.set(k, cell); }
    cell.push(n);
    return n;
  }

  _link(a, b, type, cost) {
    for (const l of a.links) if (l.node === b) return;
    const d = a.pos.distanceTo(b.pos);
    let c = cost ?? d;
    if (type === 'jump') c = d + 1.2;
    else if (type === 'drop') c = d + 0.4;
    a.links.push({ node: b, to: -1, cost: Math.max(c, d), type });
  }

  _padAt(x, y, z, grow = 0) {
    const pads = this.pads;
    for (let i = 0; i < pads.length; i++) {
      const p = pads[i];
      if (x > p.min.x - grow && x < p.max.x + grow && z > p.min.z - grow && z < p.max.z + grow && y >= p.min.y - 0.35 && y < p.max.y) return i;
    }
    return -1;
  }

  _isDynamic(c) {
    return !!c && (c.barrelId !== undefined || c.lampId !== undefined || c.glass === true);
  }

  /** Feet height at which a character of half-width r can stand at (x,z) on/near surface sy, or NaN. */
  _standAt(x, sy, z, r) {
    const w = this.world, o = this.opts;
    let y = sy;
    for (let k = 0; k < 3; k++) {
      if (w.isFree(x, y, z, r, o.height)) break;
      const g = w.groundHeight(x, y, z, r, o.stepUp, o.stepUp + 0.05);
      if (!g || g.y <= y + 1e-3 || this._isDynamic(g.collider)) return NaN;
      y = g.y;
    }
    if (y - sy > 1.0 || !w.isFree(x, y, z, r, o.height)) return NaN;
    for (const [cx, cz] of CORNERS) {
      if (!w.groundHeight(x + cx, y + 0.5, z + cz, 0.04, 0, 1.1)) return NaN;
    }
    return y;
  }

  _hasNodeNear(x, y, z, rh, rv) {
    const s = this.opts.spacing;
    const cx = Math.round(x / s), cz = Math.round(z / s);
    for (let dx = -1; dx <= 1; dx++) {
      for (let dz = -1; dz <= 1; dz++) {
        const cell = this._buildGrid.get(cellKey(cx + dx, cz + dz));
        if (!cell) continue;
        for (const n of cell) {
          if (Math.abs(n.pos.y - y) <= rv && Math.hypot(n.pos.x - x, n.pos.z - z) <= rh) return n;
        }
      }
    }
    return null;
  }

  _trySurface(x, sy, z, collider) {
    if (this._isDynamic(collider)) return;
    if (this._padAt(x, sy, z, 0.5) >= 0) return; // pads get their own centered node
    const w = this.world;
    let px = x, pz = z;
    let y = this._standAt(x, sy, z, this.opts.radius);
    if (Number.isNaN(y)) {
      for (const [nx, nz] of NUDGES) {
        const qx = x + nx, qz = z + nz;
        const g = w.groundHeight(qx, sy + 0.3, qz, 0.05, 0, 0.7);
        if (!g || Math.abs(g.y - sy) > 0.35 || this._isDynamic(g.collider)) continue;
        if (this._padAt(qx, g.y, qz, 0.5) >= 0) continue;
        const yy = this._standAt(qx, g.y, qz, this.opts.radius);
        if (!Number.isNaN(yy)) { y = yy; px = qx; pz = qz; break; }
      }
      if (Number.isNaN(y)) return;
    }
    if (this._hasNodeNear(px, y, pz, 0.55, 0.4)) return;
    this._addNode(px, y, pz);
  }

  /** Make sure a node exists at (or right next to) an important position. */
  _seed(pos) {
    const w = this.world;
    const near = this._hasNodeNear(pos.x, pos.y, pos.z, 0.3, 0.35);
    if (near) return near;
    const tryAt = (x, z) => {
      const g = w.groundHeight(x, pos.y + 0.45, z, 0.05, 0, 1.6);
      if (!g || this._isDynamic(g.collider)) return null;
      if (this._padAt(x, g.y, z, 0.3) >= 0) return null;
      const y = this._standAt(x, g.y, z, this.opts.radius);
      return Number.isNaN(y) ? null : y;
    };
    let y = tryAt(pos.x, pos.z), px = pos.x, pz = pos.z;
    if (y === null) {
      for (const [nx, nz] of NUDGES) {
        const yy = tryAt(pos.x + nx * 0.8, pos.z + nz * 0.8);
        if (yy !== null) { y = yy; px = pos.x + nx * 0.8; pz = pos.z + nz * 0.8; break; }
      }
    }
    if (y === null) return null;
    const near2 = this._hasNodeNear(px, y, pz, 0.3, 0.35);
    return near2 || this._addNode(px, y, pz);
  }

  /**
   * Sweep a walking capsule from a to b. Returns { rise, fall } (largest single step up / down)
   * or null if blocked, falling, or crossing a jump pad (other than `padOk`).
   */
  _walkTest(a, b, half, padOk = -1, maxFall = 0.62) {
    const w = this.world, o = this.opts;
    const dx = b.x - a.x, dz = b.z - a.z;
    const n = Math.max(1, Math.ceil(Math.hypot(dx, dz) / o.sample));
    let y = a.y, rise = 0, fall = 0;
    for (let k = 1; k <= n; k++) {
      const t = k / n;
      const x = a.x + dx * t, z = a.z + dz * t;
      const g = w.groundHeight(x, y, z, half, o.stepUp + 0.01, o.stepUp + 0.01 + maxFall);
      if (!g) return null;
      const pi = this._padAt(x, g.y, z);
      if (pi >= 0 && pi !== padOk) return null;
      if (!w.isFree(x, g.y, z, half, o.height - 0.05)) return null;
      const dy = g.y - y;
      if (dy > rise) rise = dy;
      if (-dy > fall) fall = -dy;
      y = g.y;
    }
    if (Math.abs(y - b.y) > 0.3) return null;
    return { rise, fall };
  }

  /** Walk off an edge from a and land on b (lower). */
  _dropTest(a, b, half) {
    const w = this.world, o = this.opts;
    const dx = b.x - a.x, dz = b.z - a.z;
    const n = Math.max(2, Math.ceil(Math.hypot(dx, dz) / o.sample));
    let y = a.y, fell = false;
    for (let k = 1; k <= n; k++) {
      const t = k / n;
      const x = a.x + dx * t, z = a.z + dz * t;
      if (!fell) {
        const g = w.groundHeight(x, y, z, half, o.stepUp, o.stepUp + 0.62);
        if (g) {
          if (this._padAt(x, g.y, z) >= 0) return false;
          if (!w.isFree(x, g.y, z, half, o.height - 0.05)) return false;
          y = g.y;
          continue;
        }
        fell = true;
      }
      // falling: the column between the landing level and the current level must be open
      const top = y + o.height;
      const g2 = w.groundHeight(x, y + 0.01, z, half, 0, y - b.y + 0.4);
      const floor = g2 ? g2.y : b.y;
      if (floor > b.y + 0.35 && k < n) return false; // something in between (we only allow clean drops)
      if (!w.isFree(x, Math.max(floor, b.y) + 0.02, z, half, top - Math.max(floor, b.y) - 0.02)) return false;
      if (this._padAt(x, floor, z) >= 0) return false;
    }
    if (!fell) return false;
    const land = w.groundHeight(b.x, b.y + 0.3, b.z, half, 0, 0.7);
    return !!land && Math.abs(land.y - b.y) < 0.35;
  }

  /** Walk from a toward a ledge, mantle up onto it and continue to b (higher). */
  _jumpTest(a, b, half) {
    const w = this.world, o = this.opts;
    const rise = b.y - a.y;
    if (!w.isFree(a.x, a.y, a.z, half, rise + o.crouchHeight + 0.1)) return false; // headroom for the jump
    const dx = b.x - a.x, dz = b.z - a.z;
    const n = Math.max(2, Math.ceil(Math.hypot(dx, dz) / o.sample));
    let y = a.y, phase = 0, px = a.x, pz = a.z;
    for (let k = 1; k <= n; k++) {
      const t = k / n;
      const x = a.x + dx * t, z = a.z + dz * t;
      if (phase === 0) {
        const g = w.groundHeight(x, y, z, half, o.stepUp, o.stepUp + 0.62);
        if (g && w.isFree(x, g.y, z, half, o.height - 0.05) && this._padAt(x, g.y, z) < 0) { y = g.y; px = x; pz = z; continue; }
        const l = w.groundHeight(x, b.y + 0.3, z, half, 0, 0.6);
        if (!l || this._isDynamic(l.collider)) return false;
        const up = l.y - y;
        if (up < 0.3 || up > o.jumpMax + 0.05) return false;
        if (!w.isFree(x, l.y + 0.02, z, half * 0.85, o.crouchHeight)) return false;
        if (!w.isFree(px, y, pz, half * 0.85, up + o.crouchHeight + 0.05)) return false;
        phase = 1;
        y = l.y;
      } else {
        const g = w.groundHeight(x, y, z, half, o.stepUp, o.stepUp + 0.62);
        if (!g || this._padAt(x, g.y, z) >= 0) return false;
        if (!w.isFree(x, g.y + 0.02, z, half * 0.85, o.crouchHeight)) return false;
        y = g.y;
      }
    }
    return phase === 1 && Math.abs(y - b.y) < 0.3;
  }

  /** Ballistic jump pad flight using the same collision response as PlayerSim. */
  _simulatePad(pad, x, y, z) {
    const w = this.world, o = this.opts;
    const pos = new THREE.Vector3(x, y + 0.01, z);
    const vel = pad.velocity.clone();
    const delta = new THREE.Vector3();
    const dt = 1 / 60;
    let air = 0, length = 0;
    const prev = new THREE.Vector3();
    for (let i = 0; i < 600; i++) {
      vel.y = Math.max(-40, vel.y - o.gravity * dt);
      delta.copy(vel).multiplyScalar(dt);
      prev.copy(pos);
      const res = w.moveCharacter(pos, delta, o.radius, o.height, { stepHeight: o.stepUp, canStep: air < 0.2 });
      air += dt;
      length += prev.distanceTo(pos);
      if (res.hitCeiling && vel.y > 0) vel.y = 0;
      if (res.hitWall) {
        const nrm = res.wallNormal;
        const dot = vel.x * nrm.x + vel.z * nrm.z;
        if (dot < 0) { vel.x -= nrm.x * dot; vel.z -= nrm.z * dot; }
      }
      if (res.onGround && vel.y <= 0.5 && air > 0.1) return { pos: pos.clone(), time: air, length };
    }
    return null;
  }

  _nearestBuild(pos, rh, rv, exclude) {
    let best = null, bestD = Infinity;
    for (const n of this._tmpNodes) {
      if (n === exclude || n.pad >= 0) continue;
      const dv = Math.abs(n.pos.y - pos.y);
      if (dv > rv) continue;
      const dh = Math.hypot(n.pos.x - pos.x, n.pos.z - pos.z);
      if (dh > rh) continue;
      const d = dh + dv * 2;
      if (d < bestD && this._clear(pos, n.pos)) { bestD = d; best = n; }
    }
    return best;
  }

  _finalize() {
    const tmp = this._tmpNodes;
    const N = tmp.length;
    // undirected components
    const comp = new Int32Array(N).fill(-1);
    const undirected = tmp.map(() => []);
    for (const a of tmp) for (const l of a.links) { undirected[a.id].push(l.node.id); undirected[l.node.id].push(a.id); }
    let best = -1, bestSize = 0, c = 0;
    const stack = [];
    for (let i = 0; i < N; i++) {
      if (comp[i] >= 0) continue;
      let size = 0;
      stack.push(i); comp[i] = c;
      while (stack.length) {
        const v = stack.pop(); size++;
        for (const u of undirected[v]) if (comp[u] < 0) { comp[u] = c; stack.push(u); }
      }
      if (size > bestSize) { bestSize = size; best = c; }
      c++;
    }
    // directed reachability from the main component (pad landings etc.)
    const keep = new Uint8Array(N);
    for (let i = 0; i < N; i++) if (comp[i] === best) { keep[i] = 1; stack.push(i); }
    while (stack.length) {
      const v = stack.pop();
      for (const l of tmp[v].links) if (!keep[l.node.id]) { keep[l.node.id] = 1; stack.push(l.node.id); }
    }
    const remap = new Int32Array(N).fill(-1);
    const nodes = [];
    for (let i = 0; i < N; i++) {
      if (!keep[i]) continue;
      remap[i] = nodes.length;
      nodes.push(tmp[i]);
    }
    const st = this.stats;
    st.walk = st.jump = st.drop = st.pad = 0;
    for (const n of nodes) {
      n.id = remap[n.id];
    }
    for (const n of nodes) {
      const links = [];
      for (const l of n.links) {
        if (!l.node || l.node.id < 0 || nodes[l.node.id] !== l.node) continue;
        links.push({ to: l.node.id, cost: l.cost, type: l.type });
        st[l.type]++;
      }
      n.links = links;
    }
    this.nodes = nodes;
    st.nodes = nodes.length;
    st.links = st.walk + st.jump + st.drop + st.pad;
    st.pruned = N - nodes.length;
    // runtime spatial hash
    this._grid.clear();
    const s = this.opts.spacing;
    for (const n of nodes) {
      const k = cellKey(Math.floor(n.pos.x / s), Math.floor(n.pos.z / s));
      let cell = this._grid.get(k);
      if (!cell) { cell = []; this._grid.set(k, cell); }
      cell.push(n.id);
    }
    // A* scratch
    this._gScore = new Float64Array(nodes.length);
    this._from = new Int32Array(nodes.length);
    this._fromType = new Int8Array(nodes.length);
    this._seen = new Uint32Array(nodes.length);
    this._closed = new Uint32Array(nodes.length);
    this._stamp = 0;
  }

  /** Movement-blocking line test between two feet positions (+0.5 m up). */
  _clear(a, b) {
    _o.set(a.x, a.y + 0.5, a.z);
    _d.set(b.x - a.x, b.y - a.y, b.z - a.z);
    const len = _d.length();
    if (len < 1e-3) return true;
    _d.divideScalar(len);
    const hit = this.world.raycast(_o, _d, len, { moveOnly: true });
    return !hit || !hit.collider;
  }

  // ------------------------------------------------------------------ queries
  /** Nearest node with line of sight from pos (+0.5 m up), preferring similar height. */
  nearest(pos, maxDist = 8, needSight = true) {
    const s = this.opts.spacing;
    const R = Math.ceil(maxDist / s);
    const cx = Math.floor(pos.x / s), cz = Math.floor(pos.z / s);
    const cand = this._cand;
    cand.length = 0;
    for (let dx = -R; dx <= R; dx++) {
      for (let dz = -R; dz <= R; dz++) {
        const cell = this._grid.get(cellKey(cx + dx, cz + dz));
        if (!cell) continue;
        for (let i = 0; i < cell.length; i++) {
          const n = this.nodes[cell[i]];
          const dh = Math.hypot(n.pos.x - pos.x, n.pos.z - pos.z);
          if (dh > maxDist) continue;
          const dy = n.pos.y - pos.y;
          if (Math.abs(dy) > maxDist) continue;
          // nodes above are much harder to reach than nodes slightly below
          const score = dh + (dy > 0 ? Math.max(0, dy - 0.5) * 4 : Math.max(0, -dy - 0.6) * 2.2);
          cand.push(score, n.id);
        }
      }
    }
    const count = cand.length / 2;
    if (!count) return null;
    // selection of the best few by score (count is small)
    const tries = Math.min(count, needSight ? 14 : 1);
    for (let t = 0; t < tries; t++) {
      let bi = -1, bs = Infinity;
      for (let i = 0; i < count; i++) if (cand[i * 2] < bs) { bs = cand[i * 2]; bi = i; }
      if (bi < 0) break;
      cand[bi * 2] = Infinity;
      const n = this.nodes[cand[bi * 2 + 1]];
      if (!needSight || this._clear(pos, n.pos)) return n;
    }
    return null;
  }

  /** A* from the node nearest fromPos to the node nearest toPos. Returns [{ pos, type }] (start excluded) or null. */
  findPath(fromPos, toPos) {
    if (!this.nodes.length) return null;
    const start = this.nearest(fromPos, 8) || this.nearest(fromPos, 14, false);
    const goal = this.nearest(toPos, 8) || this.nearest(toPos, 14, false);
    if (!start || !goal) return null;
    const ids = this._astar(start.id, goal.id);
    if (!ids) return null;
    const raw = [];
    for (let i = 1; i < ids.length; i++) raw.push({ pos: this.nodes[ids[i]].pos.clone(), type: TYPE_NAME[this._fromType[ids[i]]], node: ids[i] });
    // The start node is behind us when we're already past it: drop it if the next waypoint is directly walkable.
    const out = this._smooth(fromPos, start, raw);
    // final approach to the exact target
    const last = out.length ? out[out.length - 1].pos : start.pos;
    const dh = Math.hypot(toPos.x - last.x, toPos.z - last.z);
    if (dh > 0.5 && dh < 3 && Math.abs(toPos.y - last.y) < 0.6 && this._walkTest(last, toPos, this.opts.radius, -1)) {
      out.push({ pos: toPos.clone(), type: 'walk', node: -1 });
    } else if (!out.length) {
      out.push({ pos: goal.pos.clone(), type: 'walk', node: goal.id });
    }
    return out;
  }

  _smooth(fromPos, start, raw) {
    const out = [];
    const r = this.opts.radius;
    const maxD = this.opts.smoothRange;
    let anchor = fromPos;
    // can we walk straight from where we are? otherwise go through the start node first
    if (raw.length && raw[0].type === 'walk' && !this._walkTest(fromPos, raw[0].pos, r, -1)) {
      out.push({ pos: start.pos.clone(), type: 'walk', node: start.id });
      anchor = start.pos;
    }
    let i = 0;
    while (i < raw.length) {
      const w = raw[i];
      if (w.type !== 'walk') { out.push(w); anchor = w.pos; i++; continue; }
      let j = i;
      while (j + 1 < raw.length && raw[j + 1].type === 'walk') {
        const c = raw[j + 1].pos;
        if (Math.hypot(c.x - anchor.x, c.z - anchor.z) > maxD) break;
        const lastNode = this.nodes[raw[j + 1].node];
        if (lastNode && lastNode.pad >= 0) break; // keep pad approach explicit
        if (!this._walkTest(anchor, c, r, -1)) break;
        j++;
      }
      out.push(raw[j]);
      anchor = raw[j].pos;
      i = j + 1;
    }
    return out;
  }

  _astar(s, g) {
    const nodes = this.nodes;
    const N = nodes.length;
    if (++this._stamp > 0xfffffff0) { this._seen.fill(0); this._closed.fill(0); this._stamp = 1; }
    const stamp = this._stamp;
    const gs = this._gScore, from = this._from, ft = this._fromType, seen = this._seen, closed = this._closed;
    const heap = this._heap, hf = this._heapF;
    heap.length = 0; hf.length = 0;
    const goal = nodes[g].pos;
    const h = (id) => nodes[id].pos.distanceTo(goal);
    gs[s] = 0; from[s] = -1; ft[s] = 0; seen[s] = stamp;
    heapPush(heap, hf, s, h(s));
    let found = false;
    let guard = 0;
    while (heap.length && guard++ < N * 8) {
      const v = heapPop(heap, hf);
      if (closed[v] === stamp) continue;
      closed[v] = stamp;
      if (v === g) { found = true; break; }
      const links = nodes[v].links;
      for (let i = 0; i < links.length; i++) {
        const l = links[i];
        const u = l.to;
        if (closed[u] === stamp) continue;
        const ng = gs[v] + l.cost;
        if (seen[u] !== stamp || ng < gs[u]) {
          seen[u] = stamp;
          gs[u] = ng;
          from[u] = v;
          ft[u] = TYPE_ID[l.type];
          heapPush(heap, hf, u, ng + h(u));
        }
      }
    }
    if (!found) return null;
    const ids = [];
    for (let v = g; v !== -1; v = from[v]) ids.push(v);
    ids.reverse();
    return ids;
  }

  /** Path length (cost) of a node path, handy for utility scoring. */
  pathCost(path, fromPos) {
    if (!path || !path.length) return Infinity;
    let c = 0;
    let p = fromPos;
    for (const w of path) { c += p.distanceTo(w.pos); p = w.pos; }
    return c;
  }

  /** Random node (optionally near a point) for patrols. */
  randomNode(rng = Math.random) {
    if (!this.nodes.length) return null;
    return this.nodes[Math.floor(rng() * this.nodes.length)];
  }
}

function heapPush(heap, hf, id, f) {
  let i = heap.length;
  heap.push(id); hf.push(f);
  while (i > 0) {
    const p = (i - 1) >> 1;
    if (hf[p] <= f) break;
    heap[i] = heap[p]; hf[i] = hf[p];
    i = p;
  }
  heap[i] = id; hf[i] = f;
}

function heapPop(heap, hf) {
  const top = heap[0];
  const lastId = heap.pop(), lastF = hf.pop();
  const n = heap.length;
  if (n > 0) {
    let i = 0;
    for (;;) {
      const l = i * 2 + 1, r = l + 1;
      let m = i, mf = lastF;
      if (l < n && hf[l] < mf) { m = l; mf = hf[l]; }
      if (r < n && hf[r] < mf) { m = r; mf = hf[r]; }
      if (m === i) break;
      heap[i] = heap[m]; hf[i] = hf[m];
      i = m;
    }
    heap[i] = lastId; hf[i] = lastF;
  }
  return top;
}

void _p;
